name: Test_calc

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]
  schedule:
   - cron: "0 0/12 * * *"
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 60
    env:
      app_name: test_calc.py
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python 3.9
        uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install ruff pytest
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Test with pytest
        continue-on-error: true
        run: |
          pytest 
      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: tests
          path: calc/**
          retention-days: 30
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@v3
        with:
          name: tests
      - name: ls 
        run: ls -la
      - name: Telegram Send Last Version
        uses: appleboy/telegram-action@master
        with:
          to: ${{ secrets.ID_CHAT }}
          token: ${{ secrets.CHAT_TOKEN }}
          document: tests.zip
